version: "2"

linters:
  default: none
  enable:
    - bodyclose
    - errcheck
    - copyloopvar
    - durationcheck
    - errorlint
    - loggercheck
    - makezero
    - misspell
    - nilerr
    - nilnil
    - noctx
    - sloglint
    - ineffassign
    - staticcheck
    - unused
