name: Go

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: "1.24"
        check-latest: true

    - name: Build
      run: go build -v ./...

    - name: Vet
      run: go vet ./...

    - name: Format Check
      run: gofmt -l .

    - name: Test
      run: go test ./...
