name: Run Gosec
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  tests:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
    - name: Checkout Source
      uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24.3'
    - name: Run Gosec Security Scanner
      uses: securego/gosec@v2.22.4
      with:
        args: ./...
