name: Latest Deps CI

permissions:
  contents: read

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  latest-deps-go-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Set up Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7
        with:
          go-version-file: go.mod

      - name: Download deps
        run: go mod download

      - name: Update dependencies to latest (CI only)
        run: go get -u -t ./...

      - name: Tidy modules after update
        run: go mod tidy

      - name: Check gofmt
        run: |
          gofmt -w $(git ls-files '*.go')
          git diff --exit-code -- '*.go'

      - name: Go vet
        run: go vet ./...

      - name: GolangCI-Lint
        uses: golangci/golangci-lint-action@ba0d7d2ec06a0ea1cb5fa41b2e4a3ab91d21278a # v9.3.0
        with:
          version: v2.12.2

      - name: Go build
        run: go build ./...

      - name: Go test
        run: go test -count=1 ./...

      - name: Go test (race)
        run: go test -race -count=1 ./...
